import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Devil's Plan",
  icons: {
    // seems like i need to convert to svg or smth for it to work - work on this later 
    icon: "/images/mask.png",
    shortcut: "/images/mask.png",
    apple: "/images/mask.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-white min-h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
